server:
  port:8080
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mlc?setUnicode=true&characterEncoding=utf8&serverTimezone=CTT
    username: root
    password: ninova
    driver-class-name: com.mysql.cj.jdbc.Driver
    max-active: 200
    max-idle: 20
    min-idle: 10
  thymeleaf:
    cache: false
  jackson:
    time-zone: GMT+8

mybatis:
  mapper-locations: classpath:dataImpl/*/*Mapper.xml

